<script>
$( document ).ready(function() {
    $( "#assets-class .tab-minors" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#assets-class .tab-majors" ).removeClass("tab-active");
        $( "#assets-class .tab-exotics" ).removeClass("tab-active");
        $( ".forex-minors" ).css("display","block");
        $( ".forex-majors" ).css("display","none");
        $( ".forex-exotics" ).css("display","none");
    });
    $( "#assets-class .tab-majors" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#assets-class .tab-minors" ).removeClass("tab-active");
        $( "#assets-class .tab-exotics" ).removeClass("tab-active");
        $( ".forex-majors" ).css("display","block");
        $( ".forex-minors" ).css("display","none");
        $( ".forex-exotics" ).css("display","none");
    });
    $( "#assets-class .tab-exotics" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#assets-class .tab-minors" ).removeClass("tab-active");
        $( "#assets-class .tab-majors" ).removeClass("tab-active");
        $( ".forex-exotics" ).css("display","block");
        $( ".forex-minors" ).css("display","none");
        $( ".forex-majors" ).css("display","none");
    });

    $( "#dynamic-leverage .tab-forex" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-forex" ).css("display","block");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
         $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-metals" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-metals" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
         $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-crypto" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
        $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-stocks" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
        $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-indices" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-indices" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
        $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-energies" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-energies" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
        $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-commodities" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-futures" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-futures" ).css("display","none");
    });
    $( "#dynamic-leverage .tab-futures" ).click(function() { 
        $(this).addClass("tab-active");
        $( "#dynamic-leverage .tab-forex" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-metals" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-crypto" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-stocks" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-indices" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-energies" ).removeClass("tab-active");
        $( "#dynamic-leverage .tab-commodities" ).removeClass("tab-active");
        $( "#dynamic-leverage .tbl-futures" ).css("display","block");
        $( "#dynamic-leverage .tbl-forex" ).css("display","none");
        $( "#dynamic-leverage .tbl-metals" ).css("display","none");
        $( "#dynamic-leverage .tbl-crypto" ).css("display","none");
        $( "#dynamic-leverage .tbl-stocks" ).css("display","none");
        $( "#dynamic-leverage .tbl-indices" ).css("display","none");
        $( "#dynamic-leverage .tbl-energies" ).css("display","none");
        $( "#dynamic-leverage .tbl-commodities" ).css("display","none");
    });
});
</script>